on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      
      - name: 'Run basic AZ CLI command'
        run: az group list
        
      - uses: azure/setup-kubectl@v3
        name: Setup kubectl
      - name: Setup kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.26'
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'aksgithubrg'
          cluster-name: 'aksgithub'
          admin: 'false'
          use-kubelogin: 'true'
      - name: Run kubectl
        run: |
          kubectl apply -f nginx.yaml
